Add plexus-xml as explicit dependency required by plexus-sec-dispatcher
Since version 4 the xml tools of plexus-utils have been moved into
plexus-xml, but plexus-utils only has an optional dependency on it.
Since org.sonatype.plexus:plexus-sec-dispatcher is compiled against
plexus-utils version 1.5 it expects the xml classes to be available and
fails with an
'java.lang.NoClassDefFoundError:
org/codehaus/plexus/util/xml/XmlStreamReader'

in org.sonatype.plexus.components.sec.dispatcher.SecUtil.read(), when
creating an instance of 'SecurityConfigurationXpp3Reader'.